/** @type {import('tailwindcss').Config} */
export default {
	content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
	theme: {
		extend: {
			fontFamily: {
				palanquin: ["Palanquin", "sans-serif"],
				montserrat: ["Montserrat", "sans-serif"],
				poppins: ['"poppins"', "sans-serif"],
				roboto: ["Roboto", "sans-serif"],
				mochiy: ['"Mochiy Pop One"', "sans-serif"],
				"headline-lg": ["Plus Jakarta Sans", "sans-serif"],
				"headline-md": ["Plus Jakarta Sans", "sans-serif"],
				"headline-sm": ["Plus Jakarta Sans", "sans-serif"],
				"display-lg": ["Plus Jakarta Sans", "sans-serif"],
				"display-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
				"body-lg": ["Inter", "sans-serif"],
				"body-md": ["Inter", "sans-serif"],
				"body-sm": ["Inter", "sans-serif"],
				"label-lg": ["Inter", "sans-serif"],
				"label-md": ["Inter", "sans-serif"],
				"label-sm": ["Inter", "sans-serif"],
			},
			fontSize: {
				"label-sm": ["10px", { lineHeight: "14px", letterSpacing: "0.04em", fontWeight: "600" }],
				"headline-lg": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "700" }],
				"body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
				"headline-md": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
				"display-lg-mobile": ["28px", { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "800" }],
				"body-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
				"body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
				"label-lg": ["14px", { lineHeight: "20px", fontWeight: "600" }],
				"label-md": ["12px", { lineHeight: "16px", fontWeight: "500" }],
				"headline-sm": ["16px", { lineHeight: "24px", fontWeight: "600" }],
				"display-lg": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "800" }],
			},
			colors: {
				primary: "#1F1F1F",
				secondary: "#AB57Fa",
				background: "#faf8ff",
				lightrose: "#df73c4",
				lightblue: "#1cd0c7",
				accent: "#1abc9c",
				richblack: "#0D0C1D",
				oxford_blue: "#161B33",
				ultra_violet: "#474973",
				lavender_bush: "#F6E8EA",

				// Lumina Design System Tokens
				"surface": "#faf8ff",
				"surface-dim": "#d2d9f4",
				"surface-bright": "#faf8ff",
				"surface-container-lowest": "#ffffff",
				"surface-container-low": "#f2f3ff",
				"surface-container": "#eaedff",
				"surface-container-high": "#e2e7ff",
				"surface-container-highest": "#dae2fd",
				"surface-variant": "#dae2fd",
				"on-surface": "#131b2e",
				"on-surface-variant": "#464555",
				"inverse-surface": "#283044",
				"inverse-on-surface": "#eef0ff",
				"outline": "#777587",
				"outline-variant": "#c7c4d8",
				"surface-tint": "#4d44e3",

				"primary-lumina": "#3525cd",
				"on-primary": "#ffffff",
				"primary-container": "#4f46e5",
				"on-primary-container": "#dad7ff",
				"primary-fixed": "#e2dfff",
				"primary-fixed-dim": "#c3c0ff",
				"on-primary-fixed": "#0f0069",
				"on-primary-fixed-variant": "#3323cc",
				"inverse-primary": "#c3c0ff",

				"secondary-lumina": "#006c4a",
				"on-secondary": "#ffffff",
				"secondary-container": "#82f5c1",
				"on-secondary-container": "#00714e",
				"secondary-fixed": "#85f8c4",
				"secondary-fixed-dim": "#68dba9",
				"on-secondary-fixed": "#002114",
				"on-secondary-fixed-variant": "#005137",

				"tertiary": "#703a00",
				"on-tertiary": "#ffffff",
				"tertiary-container": "#934e00",
				"on-tertiary-container": "#ffd2b1",
				"tertiary-fixed": "#ffdcc3",
				"tertiary-fixed-dim": "#ffb77d",
				"on-tertiary-fixed": "#2f1500",
				"on-tertiary-fixed-variant": "#6e3900",

				"error": "#ba1a1a",
				"on-error": "#ffffff",
				"error-container": "#ffdad6",
				"on-error-container": "#93000a",
			},
			spacing: {
				"space-xs": "0.25rem",
				"space-sm": "0.5rem",
				"space-md": "1rem",
				"space-lg": "1.5rem",
				"space-xl": "2rem",
				"margin": "1rem",
				"margin-md": "1.5rem",
				"margin-lg": "2rem",
				"gutter": "1rem",
				"gutter-sm": "0.75rem",
			},
			boxShadow: {
				"3xl": "0 10px 40px rgba(0, 0, 0, 0.1)",
			},
			screens: {
				wide: "1440px",
			},
		},
	},
	plugins: [],
};
